version: "3.1"
services:
    postgres:
      image: postgres
      restart: always
      container_name: ${PROJECT_NAME}-postgres
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
       - "5432:5432"

    pgadmin:
      image: dpage/pgadmin4:latest
      container_name: ${PROJECT_NAME}-pgadmin4
      ports:
        - "5050:80"
      environment:
        - GUNICORN_THREADS=1
        - PGADMIN_DEFAULT_EMAIL=admin@admin.com
        - PGADMIN_DEFAULT_PASSWORD=admin123
      depends_on:
        - postgres

    webserver:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./sourcefiles/nginx:/etc/nginx/conf.d
      ports:
       - "80:80"

    php-fpm:
      build: sourcefiles/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini